#!/bin/bash

nl_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}


WALLPAPER_URL="https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-618958.jpg"


mkdir -p ~/projects

nl_echo "Cloning laptop..."
rm -rf ~/.laptop
git clone git@github.com:markokajzer/laptop.git ~/.laptop  # &> /dev/null

nl_echo "Creating global .gitconfig..."
cp ~/.laptop/files/git/* ~


nl_echo "Installing Command Line Tools..."
xcode-select --install

if ! command -v brew >/dev/null; then
  nl_echo "Installing Brew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  nl_echo "Updating Brew..."
  brew update
fi

nl_echo "Installing Brew packages..."
packages=(
  autoconf
  automake
  readline
  openssl
  git
  zsh
  sqlite
  nodenv
)
for package in "${packages[@]}"; do
  brew install $package
done


echo
printf "Do we need Ruby? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  nl_echo "Creating .gemrc..."
  echo "gem: --no-document" >| ~/.gemrc

  brew install rbenv ruby-build

  ruby_version="$(rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//')"
  rbenv install --skip-existing "$ruby_version"
  rbenv global "$ruby_version"

  gem update --system
  gem install bundler
else
  echo "Skipping Ruby."
fi

echo
printf "Do we need Python? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  brew install python@2 python pipenv
else
  echo "Skipping Python."
fi


nl_echo "Installing Applications..."
applications=(
  flux
  google-chrome
  visual-studio-code
)
for application in "${applications[@]}"; do
  echo "Installing $application..."
  brew cask install $application
done

nl_echo "Installing fonts..."
brew tap caskroom/fonts
brew cask install font-fira-mono
brew cask install font-inconsolata-dz-for-powerline

nl_echo "Cleaning up Brew..."
brew cleanup -s
brew cask cleanup


if [[ ! -d ~/.zprezto ]]; then
  nl_echo "Installing prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  ln -s ~/.zprezto/runcoms/zlogin    ~/.zlogin
  ln -s ~/.zprezto/runcoms/zlogout   ~/.zlogout
  ln -s ~/.zprezto/runcoms/zpreztorc ~/.zpreztorc
  ln -s ~/.zprezto/runcoms/zprofile  ~/.zprofile
  ln -s ~/.zprezto/runcoms/zshenv    ~/.zshenv
  ln -s ~/.zprezto/runcoms/zshrc     ~/.zshrc
else
  nl_echo "prezto is already installed."
fi

nl_echo "Overwriting runcoms..."
cat ~/.laptop/files/prezto/.zpreztorc >| ~/.zpreztorc
cat ~/.laptop/files/prezto/.zprofile  >| ~/.zprofile
cat ~/.laptop/files/prezto/.zshrc     >| ~/.zshrc

nl_echo "Changing shell to zsh..."
chsh -s /bin/zsh


nl_echo "Changing desktop wallpaper..."
curl -o ~/.laptop/files/wallpaper.jpg $WALLPAPER_URL
osascript -e "tell application \"system events\" to set picture of every desktop to (\"/Users/$(whoami)/.laptop/files/wallpaper.jpg\" as posix file as alias)"


nl_echo "Yuhu! Installation completed."
nl_echo "Things left to do:"
echo "[ ] Set Terminal profiles"
echo "[ ] Setup 1Password"
echo "[ ] Install Postgres.app"
