#!/bin/bash

nl_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}

export HOMEBREW_NO_INSTALL_CLEANUP=1

LAPTOP_FOLDER="$HOME/laptop-init"
WALLPAPER_URL="https://w.wallhaven.cc/full/x1/wallhaven-x1rowv.jpg"


mkdir -p ~/projects

nl_echo "Cloning laptop..."
cd ~/projects || exit 1
rm -rf "$LAPTOP_FOLDER"
git clone --quiet https://github.com/markokajzer/laptop.git "$LAPTOP_FOLDER"

nl_echo "Installing Command Line Tools..."
xcode-select --install

if ! command -v brew >/dev/null; then
  nl_echo "Installing Brew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo -n "Loading Brew..."
  eval "$(/opt/homebrew/bin/brew shellenv zsh)"
else
  nl_echo "Updating Brew..."
  brew update
fi


nl_echo "Installing fonts..."
brew install --quiet --yes \
  font-fira-mono \
  font-inconsolata-dz-for-powerline


nl_echo "Installing Brew packages..."
packages=(
  autoconf
  automake
  git
  mise
  openssl
  sqlite
  zsh
)
brew install --quiet --yes "${packages[@]}"

nl_echo "Installing Applications..."
applications=(
  1password
  chatgpt
  claude
  codexbar
  github
  google-chrome
  spotify
  visual-studio-code
)
brew install --cask --quiet --yes "${applications[@]}"


echo
printf "Do we need Ruby? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  nl_echo "Creating .gemrc..."
  echo "gem: --no-document" >| ~/.gemrc

  nl_echo "Installing latest stable Ruby..."
  ruby_version="$(mise ls-remote ruby | grep -E '^\d+\.\d+\.\d+$' | tail -1)"
  mise use -g ruby@"$ruby_version"

  nl_echo "Updating RubyGems and installing bundler..."
  gem update --system
  gem install bundler
else
  echo "Skipping Ruby."
fi

echo
printf "Do we need Python? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  nl_echo "Installing latest stable Python..."
  python_version="$(mise ls-remote python | grep -E '^\d+\.\d+\.\d+$' | tail -1)"
  mise use -g python@"$python_version"

  nl_echo "Updating pip..."
  pip install --upgrade pip
else
  echo "Skipping Python."
fi



if [[ ! -d ~/.zprezto ]]; then
  nl_echo "Installing prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  ln -s ~/.zprezto/runcoms/zlogin    ~/.zlogin
  ln -s ~/.zprezto/runcoms/zlogout   ~/.zlogout
  ln -s ~/.zprezto/runcoms/zpreztorc ~/.zpreztorc
  ln -s ~/.zprezto/runcoms/zprofile  ~/.zprofile
  ln -s ~/.zprezto/runcoms/zshenv    ~/.zshenv
  ln -s ~/.zprezto/runcoms/zshrc     ~/.zshrc
else
  nl_echo "prezto is already installed."
fi

nl_echo "Cleaning up Brew..."
brew cleanup --quiet --scrub
unset HOMEBREW_NO_INSTALL_CLEANUP

nl_echo "Copying configuration files..."
(
  cd "$LAPTOP_FOLDER" || exit 1
  ./bin/copy_files_to_machine
)

if [[ -f ~/.ssh/id_rsa ]]; then
  nl_echo "SSH key already exists."
  echo "Run 'pbcopy < ~/.ssh/id_rsa.pub' and paste into GitHub"
else
  nl_echo "Generating RSA token for GitHub..."
  mkdir -p ~/.ssh
  touch ~/.ssh/config
  ssh-keygen -t rsa -b 4096 -C "markokajzer91@gmail.com"
  echo "Host *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_rsa" | tee ~/.ssh/config
  eval "$(ssh-agent -s)"
  echo "Run 'pbcopy < ~/.ssh/id_rsa.pub' and paste into GitHub"
fi

nl_echo "Changing shell to zsh..."
chsh -s /bin/zsh


nl_echo "Changing settings..."
# Disable automatic capitalization after period
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
# Disable automatic period substitution when hitting space twice
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Set super fast key repeat
# KeyRepeat values: 120, 90, 60, 30, 12, 6, 2 (smaller = faster)
defaults write NSGlobalDomain KeyRepeat -int 2
# InitialKeyRepeat: 120, 94, 68, 35, 25, 15
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Do not hide Library folder
chflags nohidden ~/Library


# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# Do not re-arrange spaces based on recent use
defaults write com.apple.dock mru-spaces -bool false

# Set Active Edges
# None = 1, Mission Control = 2, Application Windows = 3, Desktop = 4, Screen Saver = 5
# Disable Screen Saver = 6, Dashboard = 7, Sleep Mode = 10, Launchpad = 11, Notification Center = 12
# defaults write com.apple.dock wvous-bl-corner -int 3
defaults write com.apple.dock wvous-br-corner -int 4

# Disable Terminal markers
defaults write com.apple.Terminal AutoMarkPromptLines -bool false

# Always show expanded control strip on Touchbar
# defaults write com.apple.touchbar.agent PresentationModeGlobal fullControlStrip


nl_echo "Changing desktop wallpaper..."
curl -o $LAPTOP_FOLDER/files/wallpaper.jpg $WALLPAPER_URL
osascript -e "tell application \"system events\" to set picture of every desktop to (\"$LAPTOP_FOLDER/files/wallpaper.jpg\" as posix file as alias)"


nl_echo "Restarting affected applications..."
killall ControlStrip Dock Finder


nl_echo "Yuhu! Installation completed."
nl_echo "Things left to do:"
echo "[ ] Set Terminal profiles"
echo "[ ] Setup 1Password"
