#!/bin/bash

nl_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}


LAPTOP_FOLDER="$HOME/projects/laptop"
WALLPAPER_URL="https://w.wallhaven.cc/full/x1/wallhaven-x1rowv.jpg"


mkdir -p ~/projects

nl_echo "Cloning laptop..."
rm -rf $LAPTOP_FOLDER
git clone git@github.com:markokajzer/laptop.git $LAPTOP_FOLDER  # &> /dev/null

nl_echo "Creating global .gitconfig..."
cp -a $LAPTOP_FOLDER/files/git/. ~


nl_echo "Installing Command Line Tools..."
xcode-select --install

if ! command -v brew >/dev/null; then
  nl_echo "Installing Brew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/main/install)"
else
  nl_echo "Updating Brew..."
  brew update
fi


nl_echo "Installing fonts..."
brew tap homebrew/cask-fonts
brew install font-fira-mono
brew install font-inconsolata-dz-for-powerline


nl_echo "Installing Brew packages..."
packages=(
  asdf
  autoconf
  automake
  git
  openssl
  sqlite
  zsh
)
for package in "${packages[@]}"; do
  brew install $package
done

nl_echo "Installing Applications..."
applications=(
  1password
  github
  google-chrome
  spotify
  visual-studio-code
)
for application in "${applications[@]}"; do
  nl_echo "Installing $application..."
  brew cask install $application
done

echo
printf "Do we need Ruby? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  nl_echo "Creating .gemrc..."
  echo "gem: --no-document" >| ~/.gemrc

  nl_echo "Setting up asdf Ruby plugin..."
  asdf plugin add ruby

  nl_echo "Installing latest stable Ruby..."
  ruby_version="$(asdf list all ruby | grep -E '^\d+\.\d+\.\d+$' | tail -1)"
  asdf install ruby "$ruby_version"
  asdf set --home ruby "$ruby_version"

  nl_echo "Updating RubyGems and installing bundler..."
  gem update --system
  gem install bundler
else
  echo "Skipping Ruby."
fi

echo
printf "Do we need Python? [yN]  "
read -r response
if [[ "$response" = "y" ]]; then
  nl_echo "Setting up asdf Python plugin..."
  asdf plugin add python

  nl_echo "Installing latest stable Python..."
  python_version="$(asdf list all python | grep -E '^\d+\.\d+\.\d+$' | tail -1)"
  asdf install python "$python_version"
  asdf set --home python "$python_version"

  nl_echo "Updating pip..."
  pip install --upgrade pip
else
  echo "Skipping Python."
fi


nl_echo "Cleaning up Brew..."
brew cleanup -s


if [[ ! -d ~/.zprezto ]]; then
  nl_echo "Installing prezto..."
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  ln -s ~/.zprezto/runcoms/zlogin    ~/.zlogin
  ln -s ~/.zprezto/runcoms/zlogout   ~/.zlogout
  ln -s ~/.zprezto/runcoms/zpreztorc ~/.zpreztorc
  ln -s ~/.zprezto/runcoms/zprofile  ~/.zprofile
  ln -s ~/.zprezto/runcoms/zshenv    ~/.zshenv
  ln -s ~/.zprezto/runcoms/zshrc     ~/.zshrc
else
  nl_echo "prezto is already installed."
fi

nl_echo "Overwriting runcoms..."
cat $LAPTOP_FOLDER/files/prezto/.zpreztorc >| ~/.zpreztorc
cat $LAPTOP_FOLDER/files/prezto/.zprofile  >| ~/.zprofile
cat $LAPTOP_FOLDER/files/prezto/.zshrc     >| ~/.zshrc

nl_echo "Generating RSA token for GitHub..."
mkdir -p ~/.ssh
touch ~/.ssh/config
ssh-keygen -t rsa -b 4096 -C "markokajzer91@gmail.com"
echo "Host *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_rsa" | tee ~/.ssh/config
eval "$(ssh-agent -s)"
echo "Run 'pbcopy < ~/.ssh/id_rsa.pub' and paste into GitHub"

nl_echo "Changing shell to zsh..."
chsh -s /bin/zsh


nl_echo "Changing settings..."
# Disable automatic capitalization after period
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
# Disable automatic period substitution when hitting space twice
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Set super fast key repeat
# KeyRepeat values: 120, 90, 60, 30, 12, 6, 2 (smaller = faster)
defaults write NSGlobalDomain KeyRepeat -int 2
# InitialKeyRepeat: 120, 94, 68, 35, 25, 15
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Do not hide Library folder
chflags nohidden ~/Library


# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# Do not re-arrange spaces based on recent use
defaults write com.apple.dock mru-spaces -bool false

# Set Active Edges
# None = 1, Mission Control = 2, Application Windows = 3, Desktop = 4, Screen Saver = 5
# Disable Screen Saver = 6, Dashboard = 7, Sleep Mode = 10, Launchpad = 11, Notification Center = 12
# defaults write com.apple.dock wvous-bl-corner -int 3
defaults write com.apple.dock wvous-br-corner -int 4

# Disable Terminal markers
defaults write com.apple.Terminal AutoMarkPromptLines -bool false

# Always show expanded control strip on Touchbar
# defaults write com.apple.touchbar.agent PresentationModeGlobal fullControlStrip


nl_echo "Changing desktop wallpaper..."
curl -o $LAPTOP_FOLDER/files/wallpaper.jpg $WALLPAPER_URL
osascript -e "tell application \"system events\" to set picture of every desktop to (\"$LAPTOP_FOLDER/files/wallpaper.jpg\" as posix file as alias)"


nl_echo "Restarting affected applications..."
killall ControlStrip Dock Finder


nl_echo "Yuhu! Installation completed."
nl_echo "Things left to do:"
echo "[ ] Set Terminal profiles"
echo "[ ] Setup 1Password"
echo "[ ] Install Postgres.app"
